---
version: '3.3'

services:
  frontend:
    container_name: spring-task-app-client
    build: .
    volumes:
      - .:/app
    ports:
      - 4000:4000
    command: bash -c "yarn build && yarn start"
