---
version: '3.3'

services:
  frontend:
    container_name: spring-task-app-client
    restart: always
    build: .
    volumes:
      - ./src:/app/src
    ports:
      - 4000:4000
    command: bash -c "yarn build && yarn start"
